config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'

  resources :warehouses, only: [:show, :new, :create, :edit, :update] do
    post 'product_entry', on: :member
    get 'search', on: :collection, to: 'warehouses#search'
    get '/warehouses', to: redirect('/')
  end

  resources :suppliers, only: [:index, :show, :new, :create]

  resources :product_types, only: [:show, :new, :create, :edit, :update] do
    patch :change_status, on: :member
  end

  resources :product_bundles, only: [:show, :new, :create]

  resources :product_categories, only: [:index, :show, :new, :create]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :warehouses, only: [:index, :show, :create]
      resources :suppliers, only: [:index, :show, :create]
      resources :product_types, only: [:index, :show, :create]
    end
  end
end

app/controllers/api/v1/product_types_controller.rb
class Api::V1::ProductTypesController < Api::V1::ApiController
  def index
    product_types = ProductType.all
    render json: product_types.as_json(except: [:created_at, :updated_at]), status: 200
  end

  def show
    product_type = ProductType.find(params[:id])
    render json: product_type.as_json(
      except: [:created_at, :updated_at],
      methods: [:dimensions],
      include: { supplier: { except: [:created_at, :updated_at, :cnpj] } }
    ), status: 200
  end

  def create
    product_type_params = params.permit(
      :name, :weight, :length, :height,
      :width, :supplier_id, :product_category_id
    )
    pt = ProductType.new(product_type_params)
    if pt.save()
      render json: pt.as_json(except: [:created_at, :updated_at]), status: 201
    else
      render json: pt.errors.full_messages, status: 422
    end
  end
end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]

  def show
    @product_type = ProductType.find(params[:id])
    @items = @product_type.warehouse_items.group(:warehouse).count
  end

  def new
    @product_type = ProductType.new
    @suppliers = Supplier.all
    @product_categories = ProductCategory.all
  end

  def create
    @suppliers = Supplier.all
    @product_categories = ProductCategory.all
    @product_type = ProductType.new(product_type_params)

    if @product_type.save()
      redirect_to product_type_path(@product_type.id), notice: 'Modelo de produto registrado com sucesso'
    else
      flash.now[:alert] = 'Não foi possível gravar o Modelo de produto'
      render 'new'
    end
  end

  def edit
    @product_type = ProductType.find(params[:id])
    @suppliers = Supplier.all
    @product_categories = ProductCategory.all
  end

  def update
    @suppliers = Supplier.all
    @product_categories = ProductCategory.all
    @product_type = ProductType.find(params[:id])

    if @product_type.update(product_type_params)
      redirect_to product_type_path(@product_type.id), notice: 'Modelo de produto atualizado com sucesso'
    else
      flash.now[:alert] = 'Não foi possível atualizar o modelo de produto'
      render 'edit'
    end
  end

  def change_status
    product_type = ProductType.find(params[:id])
    if product_type.sellable?
      product_type.unsellable!
    else
      product_type.sellable!
    end
    redirect_to product_type_path(product_type.id)
  end

  private

  def product_type_params
    params.require(:product_type).permit(
      :name, :weight, :length, :height, :width, :supplier_id, :product_category_id
    )
  end
end

app/views/product_types/edit.html.erb
<h1>Editar Modelo de Produto</h1>

<% if @product_type.errors.any?  %>
  <span> Verifique os campos abaixo: </span>
  <ul>
    <% @product_type.errors.full_messages.each do |msg|  %>
      <li> <%= msg %> </li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @product_type do |f| %>
  <div>
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :weight, 'Peso' %>
    <%= f.text_field :weight %>
  </div>
  <div>
    <%= f.label :height, 'Altura' %>
    <%= f.text_field :height %>
  </div>
  <div>
    <%= f.label :width, 'Largura' %>
    <%= f.text_field :width %>
  </div>
  <div>
    <%= f.label :length, 'Profundidade' %>
    <%= f.text_field :length %>
  </div>
  <div>
    <%= f.label :supplier_id, 'Fornecedor' %>
    <%= f.collection_select :supplier_id, @suppliers, :id, :trading_name, { include_blank: true } %>
  </div>
   <div>
    <%= f.label :product_category_id, 'Categoria' %>
    <%= f.collection_select :product_category_id, @product_categories, :id, :name, { include_blank: true } %>
  </div>
  <%= f.submit 'Salvar' %>
<% end %>

app/views/product_types/new.html.erb
<h1>Cadastrar modelo de produto</h1>

<% if @product_type.errors.any?  %>
  <span> Verifique os campos abaixo: </span>
  <ul>
    <% @product_type.errors.full_messages.each do |msg|  %>
      <li> <%= msg %> </li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @product_type do |f| %>
  <div>
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :weight, 'Peso' %>
    <%= f.text_field :weight %>
  </div>
  <div>
    <%= f.label :height, 'Altura' %>
    <%= f.text_field :height %>
  </div>
  <div>
    <%= f.label :width, 'Largura' %>
    <%= f.text_field :width %>
  </div>
  <div>
    <%= f.label :length, 'Profundidade' %>
    <%= f.text_field :length %>
  </div>
  <div>
    <%= f.label :supplier_id, 'Fornecedor' %>
    <%= f.collection_select :supplier_id, @suppliers, :id, :trading_name, { include_blank: true } %>
  </div>
  <div>
    <%= f.label :product_category_id, 'Categoria' %>
    <%= f.collection_select :product_category_id, @product_categories, :id, :name, { include_blank: true } %>
  </div>
  <%= f.submit 'Salvar' %>
<% end %>

app/views/product_types/show.html.erb
<h1> <%= @product_type.name %> </h1>
<h2>SKU: <%= @product_type.sku %></h2>
<dl>
  <dt>Peso:</dt>
  <dd><%= @product_type.weight %> gramas</dd>
  <dt>Dimensões:</dt>
  <dd><%= @product_type.dimensions %></dd>
  <dt>Fornecedor:</dt>
  <dd><%= @product_type.supplier.trading_name if @product_type.supplier %></dd>
  <dt>Categoria:</dt>
  <dd><%= @product_type.product_category.name if @product_type.product_category %></dd>
</dl>

<h2>Status do produto:</h2>
<% if @product_type.sellable? %>
  <p><b>Disponível</b> para venda</p>
  <% if user_signed_in? %>
    <%= button_to 'Tornar insdisponível', change_status_product_type_path, { method: 'patch' } %>
  <% end %>
<% else  %>
  <p><b>Indisponível</b> para venda</p>
  <% if user_signed_in? %>
    <%= button_to 'Disponibilizar', change_status_product_type_path, { method: 'patch' } %>
  <% end %>
<% end %>


<h2>Disponível nos galpões:</h2>
<% @items.each_pair do |warehouse, quantity| %>
  <p>
    <%= link_to warehouse.name, warehouse_path(warehouse.id) %> - <%= warehouse.code %> | <%= quantity %> unidades 
  </p>
<% end %>

<%= link_to 'Voltar', @product_type.supplier %> |
<%= link_to 'Editar', edit_product_type_path %>