config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'

  resources :warehouses, only: [:show, :new, :create, :edit, :update] do
    post 'product_entry', on: :member
    get 'search', on: :collection, to: 'warehouses#search'
    get '/warehouses', to: redirect('/')
  end

  resources :suppliers, only: [:index, :show, :new, :create]

  resources :product_types, only: [:show, :new, :create, :edit, :update] do
    patch :change_status, on: :member
  end

  resources :product_bundles, only: [:show, :new, :create]

  resources :product_categories, only: [:index, :show, :new, :create]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :warehouses, only: [:index, :show, :create]
      resources :suppliers, only: [:index, :show, :create]
      resources :product_types, only: [:index, :show, :create]
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @warehouses = Warehouse.all
  end
end

app/views/home/index.html.erb
<h1 class="ls-title-intro ls-ico-list2 ls-no-bg">Galpões Cadastrados</h1>
<% if user_signed_in? %>
  <p><%= link_to 'Cadastrar novo galpão', new_warehouse_path%></p>
<% end %>

<% if user_signed_in? %>
  <div class="ls-box-filter">
    <%= form_with url: search_warehouses_path, method: :get do %>
      <%= label_tag :q, 'Busca: ', class: "ls-label-text" %>
      <%= text_field_tag :q %>
      <%= submit_tag 'Pesquisar', class: "ls-btn" %>
    <% end %>
  </div>
<% end %>

<% @warehouses.each do |w| %>
  <div class="ls-list">
    <header class="ls-list-header">
      <div class="ls-list-title col-md-4">
        <%= link_to w.name, warehouse_path(w.id) %>
        <small><%= w.code %></small>
      </div>
      <div class="col-md-3 col-md-offset-5 ls-txt-right">
        <%= link_to "Ver detalhes", warehouse_path(w.id), class: "ls-btn-primary ls-btn-sm"%>
      </div>
    </header>
  </div>
<% end %>

<hr>

<p><%= link_to 'Cadastrar modelo de produto', new_product_type_path %></p>
<p><%= link_to 'Criar novo kit de produtos', new_product_bundle_path %></p>