config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'

  resources :warehouses, only: [:show, :new, :create, :edit, :update] do
    post 'product_entry', on: :member
    get 'search', on: :collection, to: 'warehouses#search'
    get '/warehouses', to: redirect('/')
  end

  resources :suppliers, only: [:index, :show, :new, :create]

  resources :product_types, only: [:show, :new, :create, :edit, :update] do
    patch :change_status, on: :member
  end

  resources :product_bundles, only: [:show, :new, :create]

  resources :product_categories, only: [:index, :show, :new, :create]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :warehouses, only: [:index, :show, :create]
      resources :suppliers, only: [:index, :show, :create]
      resources :product_types, only: [:index, :show, :create]
    end
  end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  has_many :product_types
  has_and_belongs_to_many :warehouses

  validates :name, presence: true, uniqueness: true
end

app/controllers/product_categories_controller.rb
class ProductCategoriesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @product_categories = ProductCategory.all
  end

  def show
    @product_category = ProductCategory.find(params[:id])
  end

  def new
    @product_category = ProductCategory.new
  end

  def create
    product_category_params = params.require(:product_category).permit(:name)

    @product_category = ProductCategory.new(product_category_params)
    if @product_category.save()
      redirect_to root_path, notice: 'Categoria cadastrada com sucesso'
    else
      flash.now[:alert] = 'Falha ao cadastrar Categoria'
      render 'new'
    end
  end
end

app/views/product_categories/index.html.erb
<h1 class="ls-title-intro ls-ico-list2 ls-no-bg">Categorias de Produtos</h1>

<p><%= link_to 'Cadastrar categoria de produtos', new_product_category_path %></p>

<% if @product_categories.empty? %>
  <p>Nenhuma categoria cadastrada</p>
<% else %>

  <% @product_categories.each do |cat| %>
    <div class="ls-list">
      <header class="ls-list-header">
        <div class="ls-list-title col-md-4">
          <%= link_to cat.name, product_category_path(cat.id) %>
          <small>Produtos nessa categoria: <%= cat.product_types.count %></small>
        </div>
        <div class="col-md-3 col-md-offset-5 ls-txt-right">
          <%= link_to "Ver detalhes", product_category_path(cat.id), class: "ls-btn-primary ls-btn-sm"%>
        </div>
      </header>
    </div>
  <% end %>

<% end %>

app/views/product_categories/new.html.erb
<h1>Cadastro de categorias de produto</h1>

<%= form_with model: @product_category do |f| %>
  <div>
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %>
  </div>
  <%= f.submit 'Salvar' %>
<% end %>

app/views/product_categories/show.html.erb
<h1> <%= @product_category.name %> </h1>

<h2> Produtos nessa categoria:</h2>

<% if @product_category.product_types.empty? %>
  <p>Não existem produtos nessa categoria</p>
<% else %>

  <table class="ls-table ls-table-striped">
    <tr>
      <th scope="col">Produto</th>
      <th scope="col">SKU</th>
    </tr>
    <% @product_category.product_types.each do |p| %>
      <tr>
        <td scope="row"> <%= link_to p.name, product_type_path(p.id) %></td>
        <td scope="row"><%= p.sku %></td>
      </tr>
    <% end %>
  </table>
<% end  %>